# Generated by Django 4.0.1 on 2022-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField()),
                ('death', models.IntegerField()),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
            ],
        ),
    ]
