# Generated by Django 4.0.1 on 2022-01-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_kit_user'),
        ('main_app', '0003_state_name'),
    ]

    operations = [
    ]
