# Generated by Django 4.0.1 on 2022-01-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_merge_0003_kit_user_0003_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='user',
        ),
    ]
